### ISSUE TITLE
[Bug] When running on native wayland, UI laggs a lot

### ISSUE THREAD

**Issue by d1BG** [TibixDev/winboat#308]
### What version of WinBoat are you running?

installed on 0.8.5 (cachy repos), updated to 0.8.7 (aur)

### Your Environment

Linux Distro used: Arch Linux
Desktop Environment used: Niri 25.08 (01be0e6)
FreeRDP type and version used: 3.17.2

Im running on an RTX 3060 12GB GPU (which might be the cause).
The lag happens when using env var `ELECTRON_OZONE_PLATFORM_HINT="wayland"`

The VM and apps themself are okay, its just the Winboat UI that lags.

### Steps to Reproduce / Context

1. Set `ELECTRON_OZONE_PLATFORM_HINT="wayland"` (in my case its set globally)
2. Launch WinBoat
3. UI is really laggy

### Logs

[install.log](https://github.com/user-attachments/files/22866132/install.log)
[winboat.log](https://github.com/user-attachments/files/22866131/winboat.log) 

I dont think either of them can help a lot tho..

### Expected Behavior

The UI should run smooth.

### Current Behavior

The UI laggs like crazy, sometimes unusable.

### Possible Solution

A temporary 'fix' for me is to run with `ELECTRON_OZONE_PLATFORM_HINT="x11"` - not ideal since X11 is insecure. In addition Niri doesnt have an x11 server of its own, so something like `xwayland-satellite` is needed.

### Quality Notice

- [x] I have checked the issue tracker and verified that this bug is a unique case.

**Comment by d1BG** [comment]
Additional Stuff that i should have posted, Heres what it shows in terminal when i launch from there:
```
[68535:1011/221217.872961:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[68535:1011/221217.873009:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[68535:1011/221217.873036:ERROR:shared_image_factory.cc(898)] CreateSharedImage: could not create backing.
[68535:1011/221217.873064:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[68535:1011/221217.873081:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[68535:1011/221217.873099:ERROR:shared_image_factory.cc(898)] CreateSharedImage: could not create backing.
[68535:1011/221217.873118:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[68535:1011/221217.873136:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[68535:1011/221217.873153:ERROR:shared_image_factory.cc(898)] CreateSharedImage: could not create backing.
[68535:1011/221217.873187:ERROR:shared_image_manager.cc(401)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[68535:1011/221217.873231:ERROR:gpu_service_impl.cc(1182)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[68482:1011/221217.891092:ERROR:gpu_process_host.cc(953)] GPU process exited unexpectedly: exit_code=8704
[68612:1011/221218.033678:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[68612:1011/221218.033711:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[68612:1011/221218.033728:ERROR:shared_image_factory.cc(898)] CreateSharedImage: could not create backing.
[68612:1011/221218.033747:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[68612:1011/221218.033762:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[68612:1011/221218.033776:ERROR:shared_image_factory.cc(898)] CreateSharedImage: could not create backing.
[68612:1011/221218.033791:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[68612:1011/221218.033805:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[68612:1011/221218.033818:ERROR:shared_image_factory.cc(898)] CreateSharedImage: could not create backing.
[68612:1011/221218.033843:ERROR:shared_image_manager.cc(401)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[68612:1011/221218.033869:ERROR:gpu_service_impl.cc(1182)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[68482:1011/221218.046297:ERROR:gpu_process_host.cc(953)] GPU process exited unexpectedly: exit_code=8704
[68675:1011/221218.186949:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[68675:1011/221218.186985:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[68675:1011/221218.187008:ERROR:shared_image_factory.cc(898)] CreateSharedImage: could not create backing.
[68675:1011/221218.187032:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[68675:1011/221218.187050:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[68675:1011/221218.187065:ERROR:shared_image_factory.cc(898)] CreateSharedImage: could not create backing.
[68675:1011/221218.187080:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[68675:1011/221218.187095:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[68675:1011/221218.187109:ERROR:shared_image_factory.cc(898)] CreateSharedImage: could not create backing.
[68675:1011/221218.187131:ERROR:shared_image_manager.cc(401)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[68675:1011/221218.187160:ERROR:gpu_service_impl.cc(1182)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[68482:1011/221218.196015:ERROR:gpu_process_host.cc(953)] GPU process exited unexpectedly: exit_code=8704
```

**Comment by TGlide** [comment]
same here on an amd gpu, also using niri. the fix also works for me

**Comment by redredkrovy** [comment]
Same issue here with Omarchy an Arch distro that uses Hyprland.  Fix worked for me also.

For anyone having the same issue on this distro I copied the `winboat.desktop` from `/usr/share/applications` to `~/.local/share/applications` and then change the exec command to `Exec=env = ELECTRON_OZONE_PLATFORM_HINT,"x11" /opt/winboat/winboat %U`

**Comment by d1BG** [comment]
> same here on an amd gpu, also using niri. the fix also works for me

Weird, I expected Nvidia to be the issue *again*, but I am apparently wrong

**Comment by DADA30000** [comment]
> > same here on an amd gpu, also using niri. the fix also works for me
> 
> Weird, I expected Nvidia to be the issue _again_, but I am apparently wrong

this is just issue with electron, idk why winboat picked it for their UI, should've picked Tauri, or even better, some native framework like Qt, GTK and others

**Comment by d1BG** [comment]
> this is just issue with electron, idk why winboat picked it for their UI, should've picked Tauri, or even better, some native framework like Qt, GTK and others

Other electron apps work fine tho, Like Discord (Vesktop/Equibop) or Signal Desktop for example. 
Tauri apps are VERY problematic on Nvidia GPUs (at least on my system), so its not a great recommendation either. You cant expect a project to just change their whole UI framework, if electron is what they picked then thats what the dev is most comfortable with - The fact is that theres a problem with the wayland side of things that should be looked into.

**Comment by DADA30000** [comment]
> > this is just issue with electron, idk why winboat picked it for their UI, should've picked Tauri, or even better, some native framework like Qt, GTK and others
> 
> Other electron apps work fine tho, Like Discord (Vesktop/Equibop) or Signal Desktop for example. Tauri apps are VERY problematic on Nvidia GPUs (at least on my system), so its not a great recommendation either. You cant expect a project to just change their whole UI framework, if electron is what they picked then thats what the dev is most comfortable with - The fact is that theres a problem with the wayland side of things that should be looked into.

it's just that on my system every electron app is buggy, and a lot of people I know also experience lags in electron apps on linux (for me it's probably because every chromium browser is also kinda laggy, not as bad as electron though), so I thought it was yet another electron issue, but if you say it's only in winboat UI, then yeah, it's probably a winboat problem
oh, and btw, I don't use this project personally, I was just checking for performance issues to see if they were resolved :P

**Comment by Motzumoto** [comment]
> Same issue here with Omarchy an Arch distro that uses Hyprland. Fix worked for me also.
> 
> For anyone having the same issue on this distro I copied the `winboat.desktop` from `/usr/share/applications` to `~/.local/share/applications` and then change the exec command to `Exec=env = ELECTRON_OZONE_PLATFORM_HINT,"x11" /opt/winboat/winboat %U`

I tried this as well and I'm still getting a really laggy ui. Do you happen have any other suggestions?

**Comment by redredkrovy** [comment]
@Motzumoto Sorry, I do not have any other suggestions.  That worked for me and still does.

`Exec=env = ELECTRON_OZONE_PLATFORM_HINT="x11" /opt/winboat/winboat %U`

That is the exec command in my winboat.desktop file.

**Comment by dnlghr** [comment]
Had to adjust the syntax in your exec line (just removed the equal sign after env)
`Exec=env ELECTRON_OZONE_PLATFORM_HINT="x11" /opt/winboat/winboat %U`

This seems to work fine for me. Appreciated.

**Comment by Motzumoto** [comment]
> [@Motzumoto](https://github.com/Motzumoto) Sorry, I do not have any other suggestions. That worked for me and still does.
> 
> `Exec=env = ELECTRON_OZONE_PLATFORM_HINT="x11" /opt/winboat/winboat %U`
> 
> That is the exec command in my winboat.desktop file.

~~Wouldnt you have to set x11 to wayland? ~~

Nevermind!

**Comment by xgui4** [comment]
same on hypland but the app does not work or respond to click when resizing in floating mode and some app just appear blank ...

**Comment by remyhuang03** [comment]
Same issue here.

I am using `Exec=env OZONE_PLATFORM=x11 LIBGL_ALWAYS_SOFTWARE=1 /opt/winboat/winboat` in my desktop file under hyprland.

The winboat dashboard UI is still laggy, and the only normally functioning app is "Windows Desktop" so that I can use Windows just like a VM (this went smooth though), but regular windows apps doesn't respond to clicks on hyprland.

**Comment by xgui4** [comment]
> Same issue here.
> 
> I am using `Exec=env OZONE_PLATFORM=x11 LIBGL_ALWAYS_SOFTWARE=1 /opt/winboat/winboat` in my desktop file under hyprland.
> 
> The winboat dashboard UI is still laggy, and the only normally functioning app is "Windows Desktop" so that I can use Windows just like a VM (this went smooth though), but regular windows apps doesn't respond to clicks on hyprland.

same issue

**Comment by lg28literconvectionmicrowaveoven** [comment]
I'm facing a similar problem with a hybrid laptop where winboat takes ~30s to open and are subsequently laggy. This has been fixed on newer electron versions. However, winboat seems to still be on electron 35 when most applications have advanced to newer versions.

**Comment by hasharmujahid** [comment]
> Same issue here with Omarchy an Arch distro that uses Hyprland. Fix worked for me also.
> 
> For anyone having the same issue on this distro I copied the `winboat.desktop` from `/usr/share/applications` to `~/.local/share/applications` and then change the exec command to `Exec=env = ELECTRON_OZONE_PLATFORM_HINT,"x11" /opt/winboat/winboat %U`

This works like a charm, thanks G!

**Comment by wendellmeset** [comment]
I had the lag issue on my laptop with Omarchy and I used the suggested tip above and it fixed the lag but the UI was abnormally large and the UI elements were out of place, for anyone who comes across this in the future and you have the same issue as me, use this Exec line instead:

`Exec=env ELECTRON_OZONE_PLATFORM_HINT=x11 GDK_SCALE=1 GDK_DPI_SCALE=1 QT_SCALE_FACTOR=1 /opt/winboat/winboat %U`
