### ISSUE TITLE
[Bug] Winboat Guest API Offline

### ISSUE THREAD

**Issue by DjagbleyEmmanuel** [TibixDev/winboat#355]
### What version of WinBoat are you running?

v0.8.7

### Your Environment

 OS: Linux Mint 22.2 x86_64 
Kernel: 6.8.0-85-generic
DE: Cinnamon 6.4.8
WM: Mutter (Muffin)
Name                     Application ID                     Version                  Branch       Origin      Installation
FreeRDP Client           com.freerdp.FreeRDP                3.17.2                   stable       flathub     system

### Steps to Reproduce / Context

Launch winboat and try starting container 

### Logs

no logs 

### Expected Behavior

<img width="1094" height="471" alt="Image" src="https://github.com/user-attachments/assets/4b3df4eb-383c-47c8-8495-0d0cb0b26591" />

### Current Behavior

Container runs perfectly fine except guest API is offline for some reason 

### Quality Notice

- [x] I have checked the issue tracker and verified that this bug is a unique case.

**Comment by Levev** [comment]
Could you follow the steps mentioned in the guide that opens when you click that little question mark next to the "Guest API - Offline" label and report back?

**Comment by desl8** [comment]
I would like to report that I am having this same issue. I tried all of the steps listed and none of them worked.

I am running Fedora 42 KDE, kernel 6.11

My app shows "Container - Created" instead of "Container - Running" but I am able to log into the container and use it like a normal desktop

**Comment by DjagbleyEmmanuel** [comment]
<img width="1168" height="850" alt="Image" src="https://github.com/user-attachments/assets/7b5d827f-b138-4eed-8af4-53b5f27ae05c" />
<img width="1455" height="952" alt="Image" src="https://github.com/user-attachments/assets/4f663fd9-a16c-4f9f-9256-9d6c6464cf85" />

It goes on and on. Btw, on first Install it worked without any issues but then i had to exit the container and tried launching it again to check something (Gut feelings that something would break)

**Comment by DjagbleyEmmanuel** [comment]
<img width="735" height="430" alt="Image" src="https://github.com/user-attachments/assets/c1f313aa-744e-4ebd-8cfe-8a0dbaa9e7d3" />

Here's the Folder for Winboat.

**Comment by desl8** [comment]
@DjagbleyEmmanuel 
I was able to fix the issue by going into settings and resetting winboat. Don't forget to docker rm the container!

**Comment by DjagbleyEmmanuel** [comment]
> [@DjagbleyEmmanuel](https://github.com/DjagbleyEmmanuel) I was able to fix the issue by going into settings and resetting winboat. Don't forget to docker rm the container!

Detailed steps would be very much helpful

**Comment by a1sadeq** [comment]
Run following command to get docker container's error & search for it 
`docker logs WinBoat `

**Comment by Quick911** [comment]
I have the same problem.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/8530697e-17a7-4707-a4e7-97847a3842a6" />

**Comment by Quick911** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/94c75af9-c69b-4c23-a3aa-a3119c922fe4" />

**Comment by DjagbleyEmmanuel** [comment]
It keeps trying to download windows os for install every time i launched Winboat when i already had it installed, and worked flawlessly on first run. how do i know this? I follow this link ((Use VNC at http://127.0.0.1:8006/ to access the Desktop))


PS: just a thought, I had it (Windows 11) installed on a separate drive partition, could that be the problem? storage's running low on my home partition so i chose another drive, an NVME?

**Comment by CorentinWicht** [comment]
> [@DjagbleyEmmanuel](https://github.com/DjagbleyEmmanuel) I was able to fix the issue by going into settings and resetting winboat. Don't forget to docker rm the container!

That did the trick for me as well, thanks !

**Comment by wolf89-cmd** [comment]
If you still would like to go Over the API and log in over the freerdp than what works for me is i login like you over the VNC and then navigat on your winboat-machine to C:\Program Files\WinBoat\resources\winboat_guest_server\ and there i start the winboat_guest_server.exe

It will open a Terminal, just let it run and minimize it. after one or two minutes the API works than fine for me.

hope this helps.

cheers

PS: this is also not an permanent fix. you have to do this after every startup.

**Comment by Levev** [comment]
You should start it as a service in the windows service manager.

**Comment by curlyel** [comment]
Well, I've similar issue as @DjagbleyEmmanuel. Guest API offline after some days of successful playing with Winboat ;-)

First: Same Linux and Winboat version as Emmanuel...
**What version of WinBoat are you running:** v0.8.7
**Your Environment OS:** Linux Mint 22.2 x86_64

It happened to me after applying an **update to "docker-compose-plugin" from version 2.40.1-1 to 2.40.**2**-1-ubunto.24.04-noble**. Maybe that's related?

Anyway, I've started VNC view and noticed, that Winboat is again downloading and installing Windows. This ended in a blank fresh Windows - without all of my installed software inside it of course. 
Even though being under developement, somehow disappointed admittedly ... :-(

I'm going to stop my experiments with Winboat for now as I still have other options to run my Windows software on but wanted to share my observation while hoping it may help to mature this great project!

**Comment by anarchy1923** [comment]
Can confirm the same on Pop!_OS 22.04 LTS. The VNC view keeps downloading and redownloading windows.

**Comment by gaboUTN34** [comment]
> <img alt="Image" width="735" height="430" src="https://private-user-images.githubusercontent.com/36385965/502987643-c1f313aa-744e-4ebd-8cfe-8a0dbaa9e7d3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE3NjkwMjcsIm5iZiI6MTc2MTc2ODcyNywicGF0aCI6Ii8zNjM4NTk2NS81MDI5ODc2NDMtYzFmMzEzYWEtNzQ0ZS00ZWJkLThjZmUtOGEwZGJhYTllN2QzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDI5VDIwMTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MzUxZjI5NGUxZjBjNzRiZGM3MjI5OTgwYjY3MmM2M2QzOTllMWRmYTc4NmZhYWUwMDNiMGQwMDUyMDc5ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XiL-cAUyYTELE3D0vcFg_Zw8UubFkmwXqoCayt4EWoI">
> Here's the Folder for Winboat.

I see you installed it on another drive instead of your main drive. I think WinBoat doesn't support installing from/to other drives (I have a mildly similar problem #429). Installing it on main drive AND having the ISO file there too is a workaround (like having the ISO on home folder and WinBoat folder in home too, as an example).

What I did to not lose my data on a new install:

1. Copy your current data.img folder to another drive as a backup.
2. Reset container from WinBoat settings.
3. Install again following previous indications and with the same iso you used previously but in your home folder or other place in your main drive. WinBoat folder should follow the same indication. (It could be necessary to configure the same user and password)
5. Wait for windows to install. After it's done, terminate the container and go to your WinBoat folder, delete the new data.img file.
6. Copy your previous data.img file and then you can use your previous system.

**Comment by DjagbleyEmmanuel** [comment]
@gaboUTN34 Trying now, i tell you how it went. Thanks

**Comment by mebogh** [comment]
Same issue here with Ubuntu 24.04.3 after 3 days of successfull testing, suddenly  WinBoat Guest API - Offline. 
Resetting and reinstalling winboat (0.8.7), and docker delivers the error below while installing windows. 

ERROR | Error: Command failed: docker compose -f /home/bo/.winboat/docker-compose.yml up -d

Terminal docker check:
CONTAINER ID   IMAGE                                         COMMAND                  CREATED             STATUS               PORTS     NAMES
151f9d52fbfd   ghcr.io/dockur/windows:5.07   "/usr/bin/tini -s /r…"   5 minutes ago    Created                               WinBoat

so I restarted the docker container: docker restart 151f9d52fbfd
Container is now running (green) but Winboat Guest API remains offline (red)

Update: I had to wait until the windows was reinstalled. Then everything works fine again.

Update 2: Today, same story again. Winboat and container remaining in red.
I tested the docker manually and it saisd that I removed the windows-iso file (which I did...)
I replaced it back under the winboat directory et voila, everythings works again.
So the windows iso file remains necessary, also after installation of windows by winBoat.

**Comment by fnxwarehouse** [comment]
not a fix but this just worked:

-Follow every step in the guide (the one you find by clicking in the question mark when Winboat Guest API is offline) 
-When you copy-paste the winboat_guest_server.zip content you must:
1) Add "C:\Program Files\Winboat" to the Windows Security exceptions 
2) Run install.bat & windows_guest_server.exe

Guest API should go online and should work whenever you launch winboat again

I just had this issue after modifying settings in windows firewall/security, have no idea what causes this nor if its related 
but windows security stopped me from launching guest_server.exe before i added it to the exceptions

had this issue in Arch with "Linux 6.17.6-zen1-1-zen" Kernel, Winboat Beta v0.8.7 running Windows 11,  I don't think this has anything to do with the bug but could be useful for when it gets investigated

**Comment by Basedadamite** [comment]
I had the problem where the API was offline AND the container exited (I am running Linux Mint 22.2 Cinnamon).
The reason for the problem was that I (accidentally) removed the Windows ISO from the WinBoat directory. I replaced the Windows ISO back into the WinBoat directory and my problem was solved.

**Comment by DjagbleyEmmanuel** [comment]
Finally got everything working! I ended up doing a clean Linux installation, made enough space on my home partition, downloaded the new alpha version, and installed it there. I’m still not sure what exactly fixed the issue.. 🤔 was it the clean install, the Winboat Alpha version, or the fact that this time I installed the Windows OS on the same partition (Home) as the Winboat software instead of a separate one? I guess I’ll never know. But overall, I’m grateful. Thanks to everyone who shared their solutions and to the creators of Winboat as well. All the best!
